### ISSUE TITLE
[Minecraft 1.20.1 - Fabric 0.16.9] In multiplayer, the mod crashes the game for players who try to interact with the books. This dont affect the host.

### ISSUE THREAD

**Issue by Dralaon** [ProfessorFichte/Archers-Expansion#1]
Title.

Im the host. I can use the 3 books and all the skills, but whenever my friends try to read the skills (using alt), craft one of the books, or try to pick a skill, their game closes giving the error below:

[21:37:15] [Render thread/ERROR]: Unhandled game exception
java.lang.UnsupportedOperationException: null
	at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
	at java.util.ImmutableCollections$AbstractImmutableMap.clear(ImmutableCollections.java:1074) ~[?:?]
	at snownee.kiwi.KiwiModules.clear(KiwiModules.java:49) ~[Kiwi-1.20.1-Fabric-11.8.26.jar:?]
	at snownee.kiwi.Kiwi.postInit(Kiwi.java:738) ~[Kiwi-1.20.1-Fabric-11.8.26.jar:?]
	at snownee.kiwi.Kiwi.clientInit(Kiwi.java:717) ~[Kiwi-1.20.1-Fabric-11.8.26.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-15099849194dcb7e.jar:?]
	at net.minecraft.class_310.handler$gcg001$fabric-lifecycle-events-v1$onStart(class_310.java:21554) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37) ~[notenoughcrashes-4.4.7+1.20.1-fabric.jar:?]
	at net.minecraft.class_310.modify$kng000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:40587) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[21:37:15] [Render thread/INFO]: Stopping!

Is the same error, over and over again.

**Comment by ProfessorFichte** [comment]
Greetings, from reading the crashlog it seems that the issue comes from the Kiwi Mod. Does this also happen with other Spell Engine Class Mod´s Spell Books? Because I created these Books through the Spell Engine API.

**Comment by Dralaon** [comment]
> Greetings, from reading the crashlog it seems that the issue comes from the Kiwi Mod. Does this also happen with other Spell Engine Class Mod´s Spell Books? Because I created these Books through the Spell Engine API.

Hello.
This doesn't happen with any other book of mods I have that use Spell Engine.
Also, Kiwi is a Lib that tends to give a lot of false positives... but I've had real incompatibilities with her. I don't know if this is the case, because as a host I didn't have this crash.

Other mods I use that don't have this problem (they all use the Spell Engine and add class books):
Witcher Class Mod
Forcemaster Class Mod
Death Knights
Berserker Class Mod
More RPG Classes
Elemental Wizards (RPG Series)
Paladins & Priests (RPG Series)
Wizards (RPG Series)
Rogue & Warriors (RPG Series)
Archers (RPG Series)

**Comment by ProfessorFichte** [comment]
I cant see a error from my side after investigating my Mod sorry. Maybe contacting the Kiwi Mod Dev helps
