### ISSUE TITLE
Not compatible with 1.21 while it says it is on Modrinth

### ISSUE THREAD

**Issue by Gbiesbroeck** [ProfessorFichte/Archers-Expansion#3]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Archers Expansion' (archers_expansion) 1.0.1-1.21.1 with any version that is compatible with:
		 - minecraft 1.21
More details:
	 - Mod 'Archers Expansion' (archers_expansion) 1.0.1-1.21.1 requires version 1.21.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![Schermafbeelding 2024-12-17 205729](https://github.com/user-attachments/assets/41fdf730-d3d3-4ade-9027-3bc925410276)

**Comment by ProfessorFichte** [comment]
Fixed with version 1.0.2 - 1.21.1

**Comment by Gbiesbroeck** [comment]
Thank you!!
